### ISSUE TITLE
Needs in sample project

### ISSUE THREAD

**Issue by xanderblinov** [badoo/MVIKotlin#1]
Add some sample project, please, for quick start.

Nice to see cases like:
- Very simple screen
- Screen with adapter
- Screen with lot of logic
- Shared logic in more then one screen

And of cause in context of library:
- Using labels
- Complex component

**Comment by arkivanov** [comment]
Hey, thanks for the request, will do it soon!

**Comment by arkivanov** [comment]
Hey! I have pushed a sample project, it's a classical todo list with detail view.
