### ISSUE TITLE
2.0.0 release - API feedback

### ISSUE THREAD

**Issue by arkivanov** [badoo/MVIKotlin#129]
I'm about to release first stable release. And any API change after the release will be very unwanted. So if somebody has any concerns it's a good time to raise them.

Personally I'm thinking about renaming `Intent` to `Msg` to avoid confusion with Android intents. But I'm not sure. Would like to hear about it as well.

Thanks!

**Comment by JWood48** [comment]
My 5 cents:

Please keep as Intent, since it is MVI and not MVM architecture...

Intent means you intent to do something, Msg is just a message...

**Comment by arkivanov** [comment]
2.0.0 is released! Thanks everyone!
