### ISSUE TITLE
Cannot find module MVIKotlin-mvikotlin

### ISSUE THREAD

**Issue by JWood48** [badoo/MVIKotlin#137]
I'm trying to use MVIKoltin on Kotlin 1.4.0, but i get this error:

Uncaught Error: Cannot find module 'MVIKotlin-mvikotlin'

I have included all the mvikotlin dependencies...

**Comment by AlexeyKorshun** [comment]
MVIKotlin is not compatible with kotlin 1.4

**Comment by arkivanov** [comment]
Yep, as mentioned above MVIKotlin uses Kotlin 1.3.72 at the moment. I will update during this week.
