### ISSUE TITLE
Issue importing MviKotlin for JS browser target (Kotlin 1.3.72)

### ISSUE THREAD

**Issue by denislfernandez** [badoo/MVIKotlin#141]
Hi,

I'm encountering an error executing the jsBrowserProductionWebpack task for a js browser target after importing MviKotlin dependencies on a multiplatform project (using Kotlin 1.3.72):

> 74% optimizing
>   74% basic module optimization
>   75% module optimization
>   75% advanced module optimization
>   76% after module optimization
>   76% basic chunk optimization
>   76% basic chunk optimization EnsureChunkConditionsPlugin
>   76% basic chunk optimization RemoveParentModulesPlugin
>   76% basic chunk optimization RemoveEmptyChunksPlugin
>   76% basic chunk optimization MergeDuplicateChunksPlugin
>   77% chunk optimization
>   77% advanced chunk optimization
>   77% advanced chunk optimization SplitChunksPlugin
>   77% advanced chunk optimization RemoveEmptyChunksPlugin
>   77% after chunk optimization
>   78% module and chunk tree optimization
>   78% after module and chunk tree optimization
>   79% basic chunk modules optimization
>   80% chunk modules optimization
>   80% chunk modules optimization ModuleConcatenationPlugin
>   80% advanced chunk modules optimization
>   81% after chunk modules optimization
>   81% module reviving
>   81% module reviving RecordIdsPlugin
>   82% module order optimization
>   82% module order optimization OccurrenceOrderModuleIdsPlugin
>   82% advanced module order optimization
>   83% before module ids
>   83% module ids
>   84% module id optimization
>   84% module id optimization
>   85% chunk reviving
>   85% chunk reviving RecordIdsPlugin
>   85% chunk order optimization
>   85% chunk order optimization OccurrenceOrderChunkIdsPlugin
>   86% before chunk ids
>   86% chunk id optimization
>   86% chunk id optimization FlagIncludedChunksPlugin
>   87% after chunk id optimization
>   88% hashing
>   88% after hashing
>   89% module assets processing
>   90% chunk assets processing
>   90% additional chunk assets processing
>   92% additional asset processing
>   92% chunk asset optimization
>   92% chunk asset optimization TerserPlugin
>   93% after chunk asset optimization
>   93% after chunk asset optimization SourceMapDevToolPlugin
>   93% after chunk asset optimization SourceMapDevToolPlugin
>   93% after chunk asset optimization SourceMapDevToolPlugin content.js generate SourceMap
>   93% after chunk asset optimization SourceMapDevToolPlugin resolve sources
>   93% after chunk asset optimization SourceMapDevToolPlugin content.js attach SourceMap
>   93% after chunk asset optimization SourceMapDevToolPlugin
>   93% asset optimization
>   94% after asset optimization
>   94% after seal
>   100%
>   Hash: 05868d80530f6fdfdf4a
>   Version: webpack 4.41.2
>   Time: 4463ms
>   Built at: 2020-08-21 21:27:27
>    2 assets
>   Entrypoint main = content.js content.js.map
>   [0] ./kotlin-dce/kotlin.js 242 KiB {0} [built]
>   [2] ./kotlin-dce/Reaktive-utils.js 2.41 KiB {0} [built]
>   [3] ./kotlin-dce/kotlinx-coroutines-core.js 270 KiB {0} [built]
>   [4] multi ./kotlin-dce/untitled5-content.js 28 bytes {0} [built]
>   [5] ./kotlin-dce/untitled5-content.js 2.82 KiB {0} [built]
>   [6] ./kotlin-dce/MVIDroid-mvikotlin.js 3.16 KiB {0} [built]
>   [7] ./kotlin-dce/MVIKotlin-mvikotlin-extensions-coroutines.js 3.18 KiB {0} [built]
>   [8] ./kotlin-dce/MVIKotlin-rx.js 761 bytes {0} [built]
>   [9] ./kotlin-dce/MVIKotlin-utils-internal.js 1.63 KiB {0} [built]
>       + 1 hidden module
> 
>   ERROR in ./kotlin-dce/MVIDroid-mvikotlin.js
>   Module not found: Error: Can't resolve 'MVIDroid-rx-internal' in 'C:\Users\denis\IdeaProjects\untitled5\build\js\packages\untitled5-content\kotlin-dce'
>    @ ./kotlin-dce/MVIDroid-mvikotlin.js 3:4-111
>    @ ./kotlin-dce/untitled5-content.js
>    @ multi ./kotlin-dce/untitled5-content.js
> 
>   ERROR in ./kotlin-dce/MVIDroid-mvikotlin.js
>   Module not found: Error: Can't resolve 'MVIDroid-utils-internal' in 'C:\Users\denis\IdeaProjects\untitled5\build\js\packages\untitled5-content\kotlin-dce'
>    @ ./kotlin-dce/MVIDroid-mvikotlin.js 3:4-111
>    @ ./kotlin-dce/untitled5-content.js
>    @ multi ./kotlin-dce/untitled5-content.js
> 
>   ERROR in ./kotlin-dce/MVIKotlin-mvikotlin-extensions-coroutines.js
>   Module not found: Error: Can't resolve 'MVIKotlin-mvikotlin' in 'C:\Users\denis\IdeaProjects\untitled5\build\js\packages\untitled5-content\kotlin-dce'
>    @ ./kotlin-dce/MVIKotlin-mvikotlin-extensions-coroutines.js 3:4-136
>    @ ./kotlin-dce/untitled5-content.js
>    @ multi ./kotlin-dce/untitled5-content.js
> 
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 27s
> 5 actionable tasks: 5 executed
> 

After investigating a bit the issue I've seen that the names on the js modules imported from bintray for MviKotlin do not match the ones generated upon building the project directly from the sources. The first screenshot shows the files imported from bintray, the second shows the ones generated when building from the MviKotlin source project

![idea64_v9CNxdbXX4](https://user-images.githubusercontent.com/2971107/90924934-aea61e80-e3f0-11ea-948f-d4834a7b7953.png)

![7zFM_TChqXc4ixr](https://user-images.githubusercontent.com/2971107/90924967-bf569480-e3f0-11ea-9f4b-daa1a6fb810d.png)

There is also a discrepancy between definitions inside the js between the two files besides the file name

![imagen](https://user-images.githubusercontent.com/2971107/90925682-f24d5800-e3f1-11ea-8e15-ac964feff7c8.png)

I've generated the related js module from the source project and imported locally for my project and the build problem seems to be resolved (building the js file using the latest code on master, 1d19db521380581f666380ee5df74ae6e811ec4e)

![idea64_v4L5SlBhv7](https://user-images.githubusercontent.com/2971107/90925124-0b093e00-e3f1-11ea-9892-355479921604.png)

Could these discrepancies be the problem when trying to use directly the bintray dependencies?

**Comment by arkivanov** [comment]
@denislfernandez This is really weird. "MVIDroid" is the previous name of the project, when it was Android only. I changed the name to "MVIKotlin" when converted to multipaltform. Search for "MVIDroid" through the project does not give any results. I will need to think about it.

**Comment by arkivanov** [comment]
@maxtox3 Since you are using MVIKotlin with JS, maybe you have any clues?

**Comment by arkivanov** [comment]
Publishing to a local repository produces proper names. Left picture is from Bintray, right is from local repo:
![image](https://user-images.githubusercontent.com/26204457/90929567-ddbc9000-e3f0-11ea-87b1-c2219f375e4a.png)

**Comment by arkivanov** [comment]
I could find "MVIDroid" in Bintray repo settings. Will try to change this before publishing the next version.

**Comment by arkivanov** [comment]
Suprisingly only "2.0.0-rc2" version is affected. Others look good. Perhaps this issue is related to Gradle 6.5, which was updated in rc2 release.

**Comment by denislfernandez** [comment]
Just checked with 2.0.0-rc1 and I can confirm that the error is gone. I'll be using a build published to a local repo for the 2.0.0-rc2 so I can have the latest changes

In case anyone meets this error while it is not fixed, a simple workaround after publishing a local build of the MviKotlin source project with the publishToMavenLocal gradle task is to add the following snippet inside the repository dependencies of the project
```
allprojects {
    repositories {
        ...
        exclusiveContent {
            forRepository {
                mavenLocal()
            }
            filter {
                includeGroup("com.arkivanov.mvikotlin")
            }
        }
    }
}
```
This will search for the MviKotlin dependencies on the local repository instead of bintray

If I can help with anything else let me know

**Comment by arkivanov** [comment]
@denislfernandez Just published `2.0.0-rc3` version, the issue seems fixed now. Not sure what was the reason, just updated repository settings in Bintray. Could you please check?

**Comment by denislfernandez** [comment]
Just checked the `2.0.0-rc3` and the build problems are gone after updating my dependencies for Kotlin 1.4.0

**Comment by arkivanov** [comment]
Closing this issue. Will keep an eye in future publications. Thanks for reporting!
