### ISSUE TITLE
Update Kotlin to 1.4.10

### ISSUE THREAD

**Issue by arkivanov** [badoo/MVIKotlin#152]

**Comment by bachlis** [comment]
Hello there,
This sounds simple enough. May I work on it?

**Comment by arkivanov** [comment]
@bachlis Absolutely! Thanks!

**Comment by arkivanov** [comment]
Just bump the version [here](https://github.com/arkivanov/MVIKotlin/blob/master/buildSrc/buildSrc/src/main/kotlin/dependencies/Deps.kt#L5)

**Comment by bachlis** [comment]
Do you have a Contributions.md or a general "how to build and run the project" document?

**Comment by arkivanov** [comment]
Closed via #162

**Comment by arkivanov** [comment]
> Do you have a Contributions.md or a general "how to build and run the project" document?

There is no contribution guidelines currently. But there are tests and CI setup, so every PR is built and covered.

**Comment by arkivanov** [comment]
To build everything locally just run `./gradlew build`
