### ISSUE TITLE
Use the new desktop Jetpack Compose for macOS time travel client

### ISSUE THREAD

**Issue by arkivanov** [badoo/MVIKotlin#167]

**Comment by AlexeyKorshun** [comment]
it is about alpha?

**Comment by arkivanov** [comment]
It is about the new Jetpack Compose for desktop! https://www.reddit.com/r/Kotlin/comments/jn6wio/wowcompose_desktop_maclinuxwin_is_now_available/
Looks like it is possible to write Java apps with bundled JVM and Jetpack Compose UI.
So we should just investigate it and possible use. The current macOS time travel client is a pure native app with UIKit. If using JVM here, we could reuse existing code from IDEA plugin and just drop the macOS specific one. And also it will make it available not only for macOS, but for Linux and potentially Windows as well. Which is super cool.

**Comment by arkivanov** [comment]
Since Compose for Desktop can be packaged for macOs, Linux and Windows, it worth to make this client generic. So it it could connect to an arbitrary host/port, not only localhost.

**Comment by arkivanov** [comment]
Clised via #251
