### ISSUE TITLE
Replace Serializable with Parcelize in sample TodoDetailsFragment

### ISSUE THREAD

**Issue by arkivanov** [badoo/MVIKotlin#169]
TodoDetailsFragment.Arguments is Serializable, better to use Parcelize.

**Comment by lukeduncan-scot** [comment]
Hi @arkivanov,

Can I pick this issue up?

**Comment by arkivanov** [comment]
Sure, go ahead!

**Comment by lukeduncan-scot** [comment]
I've submitted a PR which I think should suffice. I wasn't sure of what you expected as there's no CONTRIBUTING file in the repo. I ran the `allTests` task before committing and it passed so let's hope the Checks do to :+1:

**Comment by lukeduncan-scot** [comment]
PR is here: https://github.com/arkivanov/MVIKotlin/pull/172

I thought Github might have picked up on the issue number but I guess it didn't. I'll change my template to use `#{number}`

**Comment by arkivanov** [comment]
@LDuncAndroid thanks for your contribution!

**Comment by lukeduncan-scot** [comment]
No problem. Happy to pick up more in the future. I've been looking for a good MVI framework and will likely look into using this on a project.
