### ISSUE TITLE
Conditional GH Actions determined by module/sourceset/architecture

### ISSUE THREAD

**Issue by lukeduncan-scot** [badoo/MVIKotlin#173]
Just something that I thought might be worth adding. I made a small PR here that would have only affected the `sample/todo-app-android` module but the Checks that are required for the PR build all the architectures.

Just to save on some :watch:  and :moneybag: 

## References

- https://buffer.com/resources/selectively-running-android-modularized-unit-tests-on-your-ci-server/
- https://stackoverflow.com/questions/63029702/getting-git-difference-of-only-the-parent-folder

**Comment by arkivanov** [comment]
Thanks! Tests are parallelized per platform, so they are pretty fast. But I will consider this.

**Comment by arkivanov** [comment]
At the moment it's not a big dial to run all tests every time. Closing for now.
