### ISSUE TITLE
[Help] Upon List Item change in State , LazyColumn Item Not Recomposing

### ISSUE THREAD

**Issue by Shabinder** [badoo/MVIKotlin#186]
**I have following State :** 
![image](https://user-images.githubusercontent.com/44765050/108833162-6f9c9400-75f2-11eb-863b-bf4aba0348cd.png)

**An Intent which cause reducer to change state by updating list item's property,like:**
![image](https://user-images.githubusercontent.com/44765050/108833367-bb4f3d80-75f2-11eb-97bb-fa82fda79b63.png)

**Consuming the state as following in UI:** 
![image](https://user-images.githubusercontent.com/44765050/108833480-e33ea100-75f2-11eb-88ef-7e226f0bc031.png)

**ISSUE:** after state change , listItem doesn't recomposes, but if I scroll the list out of screen and bring it back (i.e., Making It Recompose) the state update reflects in Item.

Help me , how to have the desired result?,I have tried keeping everything as close to TODO sample,only this issue is left,any help would be appreciated.

**Comment by arkivanov** [comment]
@Shabinder the provided pieces of code look good, I will need a reproducer project to check.

**Comment by Shabinder** [comment]
@arkivanov  an invite to private repo has been sent to you, I appreciate your help sir, Thank You

**Comment by arkivanov** [comment]
I will check it tonight, thanks!

**Comment by Shabinder** [comment]
hey @arkivanov I think I might have figured out the issue,
upon list Item Update , I only change value of a property which is of a sealedClass Type! see below:
![image](https://user-images.githubusercontent.com/44765050/108857804-78509280-7611-11eb-9346-4a302485628d.png)

![image](https://user-images.githubusercontent.com/44765050/108857838-81416400-7611-11eb-961d-1a1f535341ac.png)

I believe recomposition only triggers when some property gets changed , but here everyvalue I update belongs to the sealed class that is DownloadStatus, hence the composable doesnt recomposes as overall the property remained **"DownloadStatus"** . 
Am I making sense?
if yes , then how may make composable aware of this ? so that upon change it may recompose?

**Comment by arkivanov** [comment]
@Shabinder From what I can see from the snippets provided, the `download` property is mutable. I did not check the reproducer yet, but if you only change the mutable property, it might not trigger re-composition.

**Comment by Shabinder** [comment]
@arkivanov  instead of just changing that mutable property , copying the whole object while assigning the new status in progress did the trick.
Thanks for your help.
