### ISSUE TITLE
Receiving output from Bootstrapper at start

### ISSUE THREAD

**Issue by sefholt** [badoo/MVIKotlin#188]
I have an activity and couple of feature fragments in my application. I would like to decide what fragment to open at start before any user input. To do that I need to do some preparations, so Bootstrapper looks like the right thing to use.

I created [simple sample](https://github.com/xpathexception/MVIKotlin/tree/bootstrapper-sample) illustrating what I'm trying to achieve, but it is not working. I don't know what is the exact problem, but `RootFragment#listOutput` is not invoking for the `Label.MakeToast`. In my application I tried to use `SimpleBootstrapper` (not working) and `SuspendBootstrapper` with or without delay before `dispatch`. Everything works as expected when there is a small delay before publish, but it is not working without it. 

In supplied sample it is just enough to move [this when block](https://github.com/xpathexception/MVIKotlin/blob/bootstrapper-sample/sample/todo-coroutines/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/coroutines/store/TodoListStoreFactory.kt#L25) to the end of the method.

At this point I don't really know is there something I missed or everything works as expected. So how can I achieve desired behaviour? 

Thanks in advance!

**Comment by arkivanov** [comment]
@xpathexception Thanks for the question. The `Bootstrapper` is executed at some point during `Store` instantiation, so like inside its constructor. At this point there are no listeners yet.

You can fix it in three ways:
1. Pass a trigger to the `Store`, so the `Bootstrapper` can wait for it
2. Use a bootstrapping `Intent` instead of the `Bootstrapper`, e.g. `Intent.Bootstrap`
2. Wait until I add manual bootstrapping, can be tracked in #189

You can pass the trigger as follows:
```kotlin
class MySuspendStoreFactory(
    ...,
    private val bootstrapTrigger: suspend () -> Unit
)

class MyReaktiveStoreFactory(
    ...,
    private val bootstrapTrigger: Completable
)
```

Then in your `Bootstrapper` you should wait for the trigger:
```kotlin
    private inner class MySuspendBootstrapperImpl : SuspendBootstrapper<Unit>() {
        override suspend fun bootstrap() {
            bootstrapTrigger() // Wait for the trigger
            dispatch(Unit)
        }
    }

    private inner class MyReaktiveBootstrapperImpl : ReaktiveBootstrapper<Unit>() {
        override fun invoke() {
            bootstrapTrigger.subscribeScoped { dispatch(Unit) } // Wait for the trigger
        }
    }
```

Supplying the coroutines trigger:
```kotlin
    private val bootstrapTrigger = Mutex(locked = true)

    MySuspendStoreFactory(
        ...,
        bootstrapTrigger = { bootstrapTrigger.lock() }
    ).create()

    bind(...) { ... }

    bootstrapTrigger.unlock() // Trigger the Bootstrapper
```

Supplying the Reaktive trigger:
```kotlin
    private val bootstrapTrigger = PublishSubject<Unit>()

    MyReaktiveStoreFactory(
        ...,
        bootstrapTrigger = bootstrapTrigger.asCompletable()
    ).create()

    bind(...) { ... }

    bootstrapTrigger.onComplete() // Trigger the Bootstrapper
```

**Comment by sefholt** [comment]
@arkivanov, thanks for your quick and detailed response! This is exactly what I needed!
