### ISSUE TITLE
MVI Kotlin (JS) is compatible/tested with which coroutines version?

### ISSUE THREAD

**Issue by Shabinder** [badoo/MVIKotlin#195]
I just did setup for my project for JS-Browser target and I am getting following issue:
![image](https://user-images.githubusercontent.com/44765050/110350298-95498480-8059-11eb-9bce-952dea44738c.png)
 
![image](https://user-images.githubusercontent.com/44765050/110350825-1f91e880-805a-11eb-8054-743e09a3a032.png)

Issue seems like a coroutines bug to me.... So I tried with with 2 different version 1.4.3 and 1.4.2 , but no luck .
So to just confirm , **MVI Kotlin + Decompose** has to be proven working with which coroutines version?

for a reproducer , @arkivanov ,you are added as a collaborator in my project's private repo. 
![image](https://user-images.githubusercontent.com/44765050/110351355-c1b1d080-805a-11eb-83a9-11571954b43e.png)

**Comment by arkivanov** [comment]
@Shabinder Seems like the invitation has expired. Could you please try once again?

**Comment by Shabinder** [comment]
> @Shabinder Seems like the invitation has expired. Could you please try once again?

sure, 1 second

**Comment by Shabinder** [comment]
@arkivanov  New Invitation sent.

**Comment by arkivanov** [comment]
As of coroutines version, the `mvikotlin-extensions-coroutines` module is the only module that depends on coroutines, the version is`1.4.2`.

**Comment by Shabinder** [comment]
> As of coroutines version, the `mvikotlin-extensions-coroutines` module is the only module that depends on coroutines, the version is`1.4.2`.

yup tried on 1.4.2 , still same error

**Comment by arkivanov** [comment]
I can't find the code in the relevant project, could you please point me on the exact location?

**Comment by arkivanov** [comment]
Sorry I was confused by the code snippet, just realised it is the MVIKotlin's code. I will check.

**Comment by arkivanov** [comment]
@Shabinder Could you please provide steps to reproduce?

**Comment by Shabinder** [comment]
> @Shabinder Could you please provide steps to reproduce?

just launch ,
`
./gradlew :web-app:browserDevelopmentRun --continuous `

after building , brower will open ,and you can navigate through the stacktrace in **console**.

**Comment by Shabinder** [comment]
I believe the bug could be maybe related to this code too,I am not sure tho...
**web-app/src/main/kotlin/extras/RenderableComponent.kt: LINE 22**

**Edit:**
I also get error when I try launching anything in Global Scope too!
you can try uncommenting line to see more errors related to this at following position:
**common/dependency-injection/src/commonMain/kotlin/com/shabinder/common/di/providers/SpotifyProvider.kt** : Line 44

**Comment by arkivanov** [comment]
@Shabinder The issue seems indeed in Coroutines or Kotlin/JS. I tried using MVIKotlin `2.0.1` with `mvikotlin-extensions-coroutines` module in Decompose Counter JS app (in shared module), it works just fine. So it looks like something specific in your project causes the error. I can't do anything at this point, unfortunately. I recommend you to do the following:
1. Report the error to [Kotlin YouTrack](https://youtrack.jetbrains.com/issues/KT). They accept private projects confidentially, or you can extract some minimal reproducer.
2. Try to reduce your code to find the real cause (I usually doing something like binary search, commenting different parts of the code).

Let's keep this issue open for a while.

**Comment by Shabinder** [comment]
@arkivanov  hey , I found the cause , but I dont Understand .....

if i override a  flow variable in class Body like below , all works fine!
![image](https://user-images.githubusercontent.com/44765050/110445902-9d9ad180-80e4-11eb-8ab6-a815f8b3edab.png)


but if I override it in constructor instead like below, it again throws error that .collect{} is not a function
![image](https://user-images.githubusercontent.com/44765050/110446143-dc308c00-80e4-11eb-9cfd-69e5981119ff.png)

what is basically the change?, **I don't Understand the real cause here....???**
🤔🤔🤔

**Comment by arkivanov** [comment]
@Shabinder this indeed looks like a compiler bug and worth reporting it to Kotlin YouTrack!

**Comment by Shabinder** [comment]
> @Shabinder this indeed looks like a compiler bug and worth reporting it to Kotlin YouTrack!

yup, I did
https://youtrack.jetbrains.com/issue/KT-45363

**Comment by arkivanov** [comment]
Thank you very much @Shabinder for investigating and reporting the issue!
