### ISSUE TITLE
Drop android() target and use plain jvm() for mvikotlin-main subproject

### ISSUE THREAD

**Issue by audkar** [badoo/MVIKotlin#196]
Can `mvikotlin-main` sub-project be plain `jvm()` target (without android)? I can't find any code which depends on Android in it or it's dependencies. My use-case would be having plain jvm feature modules in my android application.

Benefits for plain jvm feature modules:
- leaner submodules (without android gradle plugin) = faster Gradle configuration
- no separate artifact for android (`mvikotlin-main-android `)
- no need to create `AndroidManifest` per each module

**Comment by arkivanov** [comment]
Hello @audkar . MVIKotlin targets both `android` and `jvm`. So depending on your setup Gradle will keep proper dependencies.

**Comment by audkar** [comment]
Ups.. Miss-configuration on my side. Everything works.

> MVIKotlin targets both android and jvm

Still seems strange to have android target for three additional packages when no android specific implementation is used. Anyway... Really nice work on this awesome project!
