### ISSUE TITLE
Js(IR Compiler) variant support?

### ISSUE THREAD

**Issue by Shabinder** [badoo/MVIKotlin#199]
Is there support for using this in project built with IR compiler instead of Legacy as legacy leads to huge .js files and IR is more optimised than legacy.

**Comment by arkivanov** [comment]
Thanks for the question, I will consider enabling IR mode.

**Comment by Shabinder** [comment]
Maybe in **next update** of MVIKotlin and Decompose? enable support for **both compilers**...?
![image](https://user-images.githubusercontent.com/44765050/112524163-825ae200-8dc5-11eb-9587-c01146b0f8d4.png)

**Comment by arkivanov** [comment]
Yes, this is what I'm thinking about. Thanks!

**Comment by arkivanov** [comment]
I tried to enable IR mode for JavaScript but hit the following bug: [KT-42073](https://youtrack.jetbrains.com/issue/KT-42073). Same for Reaktive actually, could not enable IR mode as well. I will try to find a workaround, but at the moment I'm out of ideas.

**Comment by arkivanov** [comment]
I was able to find a workaround for [KT-42073](https://youtrack.jetbrains.com/issue/KT-42073), but got another issue: [KT-44796](https://youtrack.jetbrains.com/issue/KT-44796). I think we'll need to wait for Kotlin 1.5.

**Comment by arkivanov** [comment]
FYI: enabled JS IR Compiler for Decompose.

**Comment by Shabinder** [comment]
Hey @arkivanov,
Does #218 _(Kotlin 1.5)_ make it possible to build for IR?

**Comment by arkivanov** [comment]
Hey @Shabinder , that's actually the reason why I updated to Kotlin 1.5.0 :-) Pushed changes to #205, will see how it will build. Also just noticed that [KT-42073](https://youtrack.jetbrains.com/issue/KT-42073) has target version 1.5.20, so there will be still a workaround.

**Comment by Shabinder** [comment]
Fingers Crossed 🤞 , 
and let's hope Kotlin/JS Team catches up quick with [KT-42073](https://youtrack.jetbrains.com/issue/KT-42073)

**Comment by arkivanov** [comment]
@Shabinder version `2.0.3` is released with Kotlin `1.5.0` and JS IR mode. Please allow a few hours for Maven Central to sync everything.
