### ISSUE TITLE
Adding dependency on mvikotlin 2.0.1 in a multiplatform project, there is a gradle error about samplesources

### ISSUE THREAD

**Issue by mikezliu** [badoo/MVIKotlin#200]
When adding a gradle dependency to mvikotlin in my multiplatform's commonMain sourceset, I am getting a build error. If I add the dependency in my android app's build gradle file, I'm not seeing an error (so it seems to not be a jcenter issue). It seems to be searching for samplesources when I include the dependency in my multiplatform project.

implementation "com.arkivanov.mvikotlin:mvikotlin:2.0.1"

<ij_msg_gr>Gradle import errors<ij_msg_gr><ij_nav>/Users/user/repos/app/client/client-shared/build.gradle<ij_nav><i><b>project ':appKotlinShared': Unable to build Kotlin project configuration</b><eol>Details: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find mvikotlin-2.0.1-samplessources.jar (com.arkivanov.mvikotlin:mvikotlin:2.0.1).<eol>Searched in the following locations:<eol>    https://jcenter.bintray.com/com/arkivanov/mvikotlin/mvikotlin/2.0.1/mvikotlin-2.0.1-samplessources.jar</i>

**Comment by arkivanov** [comment]
Hi. What targets do you support? Looks like your issue is answered here: https://stackoverflow.com/questions/65892546/gradle-doesnt-look-for-dependency-in-the-right-way

**Comment by mikezliu** [comment]
I'm currently supporting these targets in my multiplatform project:

commonMain, jvmMain, iosMain, iosArm32Main, iosArm64Main

commonTest, iosArm32Test, iosArm64Test

Thanks for the link - taking a look

**Comment by arkivanov** [comment]
As written in the readme, only the following targets are currently supported: Android, JVM, JavaScript, iosX64, iosArm64, macosX64, linuxX64

**Comment by mikezliu** [comment]
Got it, thanks
