### ISSUE TITLE
Describe Results and Labels in more detail in the documentation

### ISSUE THREAD

**Issue by arkivanov** [badoo/MVIKotlin#207]

**Comment by dalewking** [comment]
I think Labels is a confusing name, I call them Events as they say an event occurred but do not affect the current state

**Comment by arkivanov** [comment]
Event is usually used by View, to avoid clashing I came up with Label naming. Another variant was Effect, but Label won as more neutral.

**Comment by arkivanov** [comment]
Closed via #214
