### ISSUE TITLE
Best practice for sharing strings across platforms

### ISSUE THREAD

**Issue by sgallese** [badoo/MVIKotlin#21]
Is there a best practice to share text resource strings across projects?
For example, I have a button with the text label "Add".
I want to share this text across iOS and Android.

**Comment by Alex009** [comment]
you can try [moko-resources](https://github.com/icerockdev/moko-resources)

**Comment by arkivanov** [comment]
Yeah moko-resources should work. Alternatively you can inject some sort of string provider into shared code.
