### ISSUE TITLE
Is this library compatible with apollo caching behaviour ?

### ISSUE THREAD

**Issue by ajacquierbret** [badoo/MVIKotlin#222]
@arkivanov  I'm very interested in the MVI pattern and Kotlin Multiplatform, and this library seems like a perfect fit for my project.
But being used to apollo-graphql ([apollo-android](https://github.com/apollographql/apollo-android)) and its caching features, I'm curious to know if it'd be possible to use it instead of the MVIKotlin's store interface. Do you think it's feasable ? Does anyone heard of something like that ?

**Comment by arkivanov** [comment]
The `Store` interface is the core component of the library, everything is built around it. How do you imagine using the library and at the same time using something instead of the `Store` interface?
