### ISSUE TITLE
Can't export time travel data

### ISSUE THREAD

**Issue by falcon4ever** [badoo/MVIKotlin#267]
It looks like the export option for time travel data is not working correctly. I was trying out the time travel feature using the [TodoApp project](ttps://github.com/JetBrains/compose-jb/tree/master/examples/todoapp) and the export button does not open up a dialog on where to save the data. See recording: https://youtu.be/vVxzPba4078

Dev Environment:
- Mac OS X Catalina 10.15.7
- Android Studio Arctic Fox 2020.3.1 Beta 5
- MVIKotlin Time Travel Plugin v2.0.0
- Decompose v0.2.6
- MVIKotlin v2.0.4

**Comment by arkivanov** [comment]
Hello @falcon4ever . I think this question is more relevant to MVIKotlin than Decompose, so transferred it.

The export/import feature currently only works for JVM and Android, and requires `States`, `Intents`, `Labels`, `Actions` and `Results` to be `Serializable`. The latter is not the case for the [TodoApp](https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp) example in the `compose-jb` repository. You can try the similar [todo app example](https://github.com/arkivanov/MVIKotlin/tree/master/sample) in this MVIKotlin repository, it should work fine.

I think we should explicitly mention this requirement in the docs, so I will keep this issue open. Probably some meaningful errors would be also helpful.

**Comment by falcon4ever** [comment]
Apologies, having both projects opened in the browser and I posted in the wrong one 🤦‍♂️ thanks for moving it.

Ah, thanks for the explanation! Will try out your suggestion

**Comment by arkivanov** [comment]
Closing for now, feel free to reopen if there are still any issues.
