### ISSUE TITLE
Caching of Labels if no consumers

### ISSUE THREAD

**Issue by Skeptick** [badoo/MVIKotlin#46]
Greetings again! Solution for saving `Store` is great, thanks! But I have one more question...

In the documentation for the library, you suggest using `Label` as a one-time event, and it's really very convenient. But we again encounter the Android lifecycle :(

For example, I want to notify `View` by means of `Label` about the need to display different dialogs or snackbars. But if `Label` comes when the application is in pause/stop/destroy state (depending on the `BinderLifecycleMode`), these `Label`s will be _irretrievably lost_. Perhaps a more logical solution would be to keep them while the consumer is absent? It seems to me to be quite common use case and it would be convenient to have something similar already integrated into the library.

However, if you don't share my opinion, I will try to implement something like CacheSubject and custom StoreFactory :)

**Comment by arkivanov** [comment]
Hello! Yes this might be a problem indeed. In such cases I suggest to use state instead. You can raise a flag in the state and when view will receive this it should first produce an event to dismiss this flag and then handle it. I understand that it is boilerplate but this is the proper way.

**Comment by Skeptick** [comment]
Yes, I know this way. Honestly, I always considered the need to handle one-time events through state to be the main disadvantage of the MVI pattern. Probably this method is correct for maintaining a state in a consistent form, and also allows to save a state in local storage. But... if events are not so important and do not affect the rest of the state, writing this boilerplate seems unnecessary.

I heard your point of view, thanks :) Perhaps you are right, I will think about it.

**Comment by arkivanov** [comment]
Yeah. If events are not so important it might be ok to miss them in such corner cases.

There is also a third (a bit hacky) way:
```kotlin
class OneOffValue<T: Any>(value: T) {
    private var value: T? = value

    fun get(): T? = value?.also { value = null }
}

data class MyState(
    val error: OneOffValue<String>? = null
) 
```
