### ISSUE TITLE
Add sample todo for JS

### ISSUE THREAD

**Issue by arkivanov** [badoo/MVIKotlin#53]
Would be nice to add some samples for JS. Consider using [Kotlin React wrappers](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-react).

- Implement [`TodoDatabase`](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-common/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/common/database/TodoDatabase.kt) (refer to implementations for [Android](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-common/src/androidMain/kotlin/com/arkivanov/mvikotlin/sample/todo/common/database/TodoDatabaseImpl.kt) (Persistent) and [Darwin](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-common/src/darwinCommonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/common/database/TodoDatabaseImpl.kt) (In-memory, I'm lazy). Perhaps we can share the in-memory implementation with JS.
- Implement [TodoListView](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-common/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/common/view/TodoListView.kt), [TodoAddView](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-common/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/common/view/TodoAddView.kt) and [TodoDetailsView](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-common/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/common/view/TodoDetailsView.kt). If using Kotlin React then this [view proxy trick](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-app-ios/todo-app-ios/list/TodoListViewProxy.swift) might be useful here as well.
- Reuse [`TodoListController`](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-common/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/common/controller/TodoListController.kt) and [`TodoDetailsController`](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-common/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/common/controller/TodoDetailsController.kt), either [Reaktive variant](https://github.com/arkivanov/MVIKotlin/tree/master/sample/todo-reaktive/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/reaktive/controller) or [coroutines variant](https://github.com/arkivanov/MVIKotlin/tree/master/sample/todo-coroutines/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/coroutines/controller) (or both, like in [Android sample](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-app-android/src/main/java/com/arkivanov/mvikotlin/sample/todo/android/list/TodoListFragment.kt#L36))

**Comment by maxtox3** [comment]
I want to try

**Comment by arkivanov** [comment]
Sold!

**Comment by arkivanov** [comment]
@maxtox3 added some `@JsName` annotations here: #57. Feel free to comment if you think we need to add more.

**Comment by maxtox3** [comment]
@arkivanov Ok, thanks!

**Comment by arkivanov** [comment]
A few more `@JsName` annotations added here #59

**Comment by arkivanov** [comment]
Closing details screen when Delete button is clicked implemented here #65

**Comment by arkivanov** [comment]
Closed by #58

**Comment by arkivanov** [comment]
Thanks @maxtox3 !
