### ISSUE TITLE
Logo wanted!

### ISSUE THREAD

**Issue by arkivanov** [badoo/MVIKotlin#66]
The project needs logo but I'm not good at design. I will appreciate any help here. Ideally it should highlight Kotlin and MVI (or unidirectional data flow). I'm quite flexible here.

**Comment by precious-omovoiye** [comment]
Let's connect

**Comment by precious-omovoiye** [comment]
Hi @arkivanov, I would love to work on this.

**Comment by arkivanov** [comment]
Sold! Thanks in advance!

**Comment by precious-omovoiye** [comment]
You're are welcome

**Comment by precious-omovoiye** [comment]
> The project needs logo but I'm not good at design. I will appreciate any help here. Ideally it should highlight Kotlin and MVI (or unidirectional data flow). I'm quite flexible here.

Does the project have a unique name like Angular, Laravel, Django and other frameworks?

**Comment by arkivanov** [comment]
Yes, the name is MVIKotlin.

**Comment by arkivanov** [comment]
The logo is supposed to be added to this GitHub project's README at the very top. You can check examples here: [Reaktive](https://github.com/badoo/Reaktive), [Ktor](https://github.com/ktorio/ktor), [moko-mvvm](https://github.com/icerockdev/moko-mvvm)

**Comment by precious-omovoiye** [comment]
Alright, do you have any type of logo, and colour preference in mind?

**Comment by arkivanov** [comment]
Well, nothing particular. Ideally I want it square or maybe rectangle. The primary idea is to somehow highlight the Unidirectional Data Flow. The secondary idea is to highlight Kotlin (not necessary). Colour preference would be colourful (blue, red, green, orange) but with limited amount of colours. Ideally without gradients.

Examples of random logos that I like:
<img src="https://user-images.githubusercontent.com/26204457/82728903-3d6ca780-9ceb-11ea-8687-879397189e4e.png" width="300"/> - **excluding** black ones


<img src="https://user-images.githubusercontent.com/26204457/82728958-ace29700-9ceb-11ea-8141-85348790485d.png" height="100"/> <img src="https://user-images.githubusercontent.com/26204457/82728973-d0a5dd00-9ceb-11ea-9c26-7a9b0ac3e939.png" height="100"/>

Examples of logos that I don't like: Instagram, Firefox

**Comment by precious-omovoiye** [comment]
Alright

**Comment by precious-omovoiye** [comment]
The reason you don't like Instagram and Firefox is it because of their gradient fill?

**Comment by arkivanov** [comment]
> The reason you don't like Instagram and Firefox is it because of their gradient fill?

Exactly

**Comment by precious-omovoiye** [comment]
![Logo-03](https://user-images.githubusercontent.com/48134134/83092361-0dc7f180-a095-11ea-8966-b599faa1ed69.jpg)
This is a sample, what's your thought?

**Comment by precious-omovoiye** [comment]
The intertwining of the shapes makes reference to the idea of unidirectional data flow, with the way in which the blue square intertwines onto the orange square, the viewer is compelled to go through the shape in a unidirectional manner.

**Comment by precious-omovoiye** [comment]
Let me know which style you would go with and if you have any observations, if there isn't any, then I will forward the logo in other suitable formats for use.

**Comment by kissedcode** [comment]
I suggest:
![image](https://user-images.githubusercontent.com/18675884/83139715-78a91500-a0f5-11ea-9780-7fceefc1108f.png)

**Comment by kissedcode** [comment]
![mvikotlin logo – Figma 2020-05-29 16-12-03](https://user-images.githubusercontent.com/18675884/83263386-318b5480-a1c7-11ea-9249-988db0818043.jpg)

**Comment by arkivanov** [comment]
@kissedcode Unfortunately the "K" logo can not be used, I was told it violates Kotlin Foundation guidelines: https://kotlinlang.org/foundation/guidelines.html

**Comment by arkivanov** [comment]
Also I was asked to rename the project, since "Kotlin" can not be used as well. 🤦‍♂️

**Comment by arkivanov** [comment]
@precious-omovoiye Thanks for the sample. Can we try to tweak it a bit? Maybe remove the title and keep just the icon. Also would be nice to make blue colour lighter. And maybe transform the blue line into two arrows pointing one into another. What do you think?

And maybe as an experiment, maybe we can fill the blank space in the middle somehow? Maybe add a letter "M", or something... Not sure how it will look like though.

**Comment by precious-omovoiye** [comment]
@arkivanov I will try it out and see

**Comment by precious-omovoiye** [comment]
> Also I was asked to rename the project, since "Kotlin" can not be used as well. 🤦‍♂️

@arkivanov I had this feeling that having "MVI" and "KOTLIN" which are two unambiguous names, as the title of the project wasn't a good idea, that was why I earlier asked if there was a unique name for the project, have you been able to come up with a name yet?

**Comment by arkivanov** [comment]
> > Also I was asked to rename the project, since "Kotlin" can not be used as well. man_facepalming
> 
> @arkivanov I had this feeling that having "MVI" and "KOTLIN" which are two unambiguous names, as the title of the project wasn't a good idea, that was why I earlier asked if there was a unique name for the project, have you been able to come up with a name yet?

A new name will be there soon. You can propose your ideas here: #72

**Comment by precious-omovoiye** [comment]
Alright

**Comment by Hexakosioihexekontahex** [comment]
![photo_2020-06-01_09-23-03](https://user-images.githubusercontent.com/20238244/83381660-e604c080-a3e9-11ea-8e11-abd14f2ac838.jpg)

**Comment by Hexakosioihexekontahex** [comment]
![image](https://user-images.githubusercontent.com/20238244/83383948-db98f580-a3ee-11ea-89da-92111841626d.png)

**Comment by arkivanov** [comment]
@Hexakosioihexekontahex thanks for the proposal but to me it looks very confusing. I can't find any relation between the person and a Kotlin MVI framework. Also I feel there is too much detail. I would prefer something simple and meaningful at the same time. Thanks!

**Comment by Hexakosioihexekontahex** [comment]
> @Hexakosioihexekontahex thanks for the proposal . . .
No problem!

**Comment by precious-omovoiye** [comment]
> @precious-omovoiye Thanks for the sample. Can we try to tweak it a bit? Maybe remove the title and keep just the icon. Also would be nice to make blue colour lighter. And maybe transform the blue line into two arrows pointing one into another. What do you think?
> 
> And maybe as an experiment, maybe we can fill the blank space in the middle somehow? Maybe add a letter "M", or something... Not sure how it will look like though.

Final touches are being made, once a name has been selected, I will input the name and forward the logo.

**Comment by precious-omovoiye** [comment]
I've visited the poll though

**Comment by arkivanov** [comment]
@precious-omovoiye The name is not decided yet. There is a little chance I will be able to keep the current one.

**Comment by kissedcode** [comment]
> @precious-omovoiye The name is not decided yet. There is a little chance I will be able to keep the current one.

so maybe you will be able to use Kotlin logo for your project)

**Comment by arkivanov** [comment]
> > @precious-omovoiye The name is not decided yet. There is a little chance I will be able to keep the current one.
> 
> so maybe you will be able to use Kotlin logo for your project)

This is unlikely :-(

**Comment by precious-omovoiye** [comment]
> @precious-omovoiye The name is not decided yet. There is a little chance I will be able to keep the current one.

Alright, let's see how it goes.

**Comment by arkivanov** [comment]
@precious-omovoiye I will keep the current name for now.

**Comment by precious-omovoiye** [comment]
Alright @arkivanov I will get the logo ready

**Comment by precious-omovoiye** [comment]
@arkivanov Here is the logo, the zipped file contains the landscape and portrait versions of the logo with png, svg, and jpg formats for each and a simple logo guide also. 
[MVIKOTLIN_Logo.zip](https://github.com/arkivanov/MVIKotlin/files/4805092/MVIKOTLIN_Logo.zip)

**Comment by arkivanov** [comment]
@precious-omovoiye Thanks for your contribution, I like it! There are two folders in the archive `MVIKOTLIN` and `MVIKOTLIN_Logo`, are they just duplicate?

**Comment by precious-omovoiye** [comment]
Yes they are, kindly ignore, you can just delete them
