### ISSUE TITLE
Investigate (and create?) time travel Chrome plugin for JavaScript target

### ISSUE THREAD

**Issue by arkivanov** [badoo/MVIKotlin#71]
The plugin should work similar to the IDEA time travel [plugin](https://github.com/arkivanov/MVIKotlin/tree/master/mvikotlin-timetravel-plugin-idea). It should somehow communicate to the [TimeTravelController](https://github.com/arkivanov/MVIKotlin/blob/master/mvikotlin-timetravel/src/commonMain/kotlin/com/arkivanov/mvikotlin/timetravel/controller/TimeTravelController.kt). Maybe we can implement a server similar to the [TimeTravelServer](https://github.com/arkivanov/MVIKotlin/blob/master/mvikotlin-timetravel/src/androidMain/kotlin/com/arkivanov/mvikotlin/timetravel/server/TimeTravelServer.kt) for Android. And a client similar to [TimeTravelClient](https://github.com/arkivanov/MVIKotlin/blob/master/mvikotlin-timetravel-plugin-idea/src/main/java/com/arkivanov/mvikotlin/plugin/idea/timetravel/client/TimeTravelClient.kt).

The plugin should provide controls to:
- connect to an app
- disconnect from the app
- start event recording
- stop event recording
- move to a previous state
- move to a next state
- move to a first state
- move to a last state
- cancel current time travel session

The plugin should display live event list. When an event is selected in the list, it's tree structure (values inspection) should be shown. If object parsing is not possible (in JVM it's done via reflection) then just print its `toString()`.

**Comment by maxtox3** [comment]
@arkivanov I am facing this for the first time, but I want to try

**Comment by arkivanov** [comment]
Thanks @maxtox3, let me know if you need anything!

**Comment by arkivanov** [comment]
I extracted most of the logic to common.
`:mvikotlin-timetravel-client:client-internal` - shared code for time travel clients;
`:mvikotlin-timetravel-proto-internal` - time travel protocol.

Not sure how this going to be implemented, but in general:

- a server should be in the `:mvikotlin-timetravel` module (same as for Android and Native);
- a client should be in a separate module (probably `:mvikotlin-timetravel-client:plugin-chrome`);
- the client should use the `:mvikotlin-timetravel-client:client-internal` module;
- both client and server should use same protocol from `:mvikotlin-timetravel-proto-internal`.

**Comment by arkivanov** [comment]
Alternatively we can investigate a common stand-alone client app using the new Compose for Desktop. Filed #167.

**Comment by arkivanov** [comment]
Closing this in favour of the stand-alone client app. There also well be an updated version of the app, built with Compose for Desktop.
