### ISSUE TITLE
Find another name for the project. Please suggest.

### ISSUE THREAD

**Issue by arkivanov** [badoo/MVIKotlin#72]
I was told that the name "MVIKotlin" violates [Kotlin Foundation guidelines](https://kotlinlang.org/foundation/guidelines.html). So we need to find another name for the project. Suggestions are welcome!

**Comment by arkivanov** [comment]
MVI.kt

**Comment by arkivanov** [comment]
KtMVI

**Comment by arkivanov** [comment]
MVI4Kotlin

**Comment by arkivanov** [comment]
ReactiveMVI

**Comment by ArturGajowy** [comment]
Probably a misnomer, but whatever:
rea.kt

**Comment by ArturGajowy** [comment]
rea.kt-mvi

**Comment by Hexakosioihexekontahex** [comment]
KoMVIn

**Comment by precious-omovoiye** [comment]
Alright

**Comment by TylerMcCraw** [comment]
MVKotlintent

**Comment by maxtox3** [comment]
MviK

**Comment by lcszc** [comment]
Unidirekt (if it isn't related to UDF, sorry)

**Comment by arkivanov** [comment]
Thanks guys for all your ideas! I have started a poll [here](https://www.reddit.com/r/Kotlin/comments/gvf255/what_name_is_the_best_for_a_kotlin_multiplatform/).

**Comment by arkivanov** [comment]
I'm waiting for the response from Kotlin Foundation. There is a little chance I could keep the current name.

**Comment by arkivanov** [comment]
Still thinking about it

**Comment by arkivanov** [comment]
Ok, I will keep the current name for now. If this will be raised again then I will rename to "MVI.kt". Thank you all guys for your ideas!
